### ISSUE TITLE
Space/hyphen/period in keywords

### ISSUE THREAD

**Issue by sphh** [hoedt/upsilonconf#2] opened 2022-09-16 09:25 UTC
Thanks for your wonderful `upsilonconf`!

I noticed, that it is neither possible to load a configuration file, where the keys have spaces or hyphens (periods simply adds a new level). This requires to convert all hyphens and spaces to underscores in the config file. This is not a very big problem, but often the files are more readable, if these characters are allowed in the keys.

I could think of the following approach how to tackle this drawback:

- When loading a file, convert the space and hyphen to an underscore. This should be configurable with keyword arguments to the `load(…, space='_', hyphen='_', period='_')` function (with the three keyword parameters defaulting to `None` resulting in the current behaviour).
- When saving, the same interface could be used: e.g. `save(…, space='_')` would replace underscores with spaces. If the load function uses different replacements for space/hyphen/period, it would be even possible to use something like `save(…, space='__', hyphen='_')`. Again the three keyword parameters would default to `None` resulting in the current behaviour.

What do you think? If you want, I could make a PR with these changes.

**Comment by hoedt** [comment] 2022-09-16 11:56
Thanks for reaching out!

Sounds like a useful feature to me. Also, it shouldn't add too much/unnecessary complexity.

However, I would suggest a more flexible interface using `dict`: something along the lines of `load(..., key_modifiers={" ": "_", "-": "_"})`
 This should be equally simple to implement, but it should cover a much wider variety of use cases.

Feel free to submit a PR if you want. 
Also, please do let me know if you see possible issues with my suggestions!

PS: `key_modifiers` is just a suggestion, I'm pretty sure you would be able to come up with a better name.

**Comment by sphh** [comment] 2022-09-16 12:05
Glad that you like my idea :blush:

I already started to implement it and that was the point, where I noticed, that supplying a list of replacements might be more sensible. I'll switch to it. `key_modifiers` sounds a very suitable name to me!

Just give me some minutes to change it …

**Comment by sphh** [comment] 2022-09-16 18:00
Thanks for merging #3. I believe this issue can be closed now.

**Comment by hoedt** [comment] 2022-09-18 05:09
I would have kept this issue open until it is fully implemented (including tests).

As a matter of fact, while writing the tests, I realised the sorting is quite arbitrary. There might be scenarios where you want shorter strings to evaluate first. Since dictionaries preserve order since python 3.6, we can simply use the order of the dictionaries, can't we? Any thoughts on this?

**Comment by sphh** [comment] 2022-09-18 06:04
No problem with re-opening it. I just thought, that discussions about the implementation would be held on the PR's site.

The problem as I see it, is the limitation of Python variable names to just uppercase and lowercase letters (A-Z, a-z), digits (0-9), and the underscore character (_). Reading is easy: Just replace all invalid characters with `_`, but saving is a different animal. I can not think of any replacements, which would survive a round-trip in all cases. The best I came up with, was to replace hyphens with a single underscore and spaces with two underscores:
```python3
load(…, key_modifiers={'-': '_', ' ': '__'})
save(…, key_modifiers={'_': '-', '__': ' '})
```
But this assumes, that the keys in the configuration files do not contain underscores and do not use double hyphens or spaces. That was the basis I had in mind when I decided to use the reversed sorting by length. I also thought about using regular expressions, but did not want to load the module for such a simple task. Still I think this could be a viable option (but I have not tried it!).

IMHO relying on the order of the `key_modifiers` dictionary would give unexpected results (and a lot of issues opened on github). The user might ask, why these two calls give different results?
```python3
save(…, key_modifiers={'__': ' ', '_': '-'})
save(…, key_modifiers={'_': '-', '__': ' '})
```
On the other hand, this module is not used by users but by developers, who are expected to read the API documentation!

It's a tough call! Personally I would expect that the calls above results in the same file to be written. But expectations might very …

I would have thought sorting by length should work in any case. Which test cases do not work?

**Comment by hoedt** [comment] 2022-09-18 08:53
The point is not that test cases do not work. The point is rather that I have this feeling that the sorting complicates the API and forces a certain paradigm onto the user. Both aspects also seem to be unnecessary. 

My thoughts:

 - Note that in the current implementation, the order of single-char replacement still matters (due to the stability of sorting by length).
   Therefore, the following two lines end up with different results.
   ```python
   >>> _replace_in_keys({"key 1": 1, "key-2": 2}, {" ": "-", "-": "_"})
   ... {"key_1": 1, "key_2": 2}
   >>> _replace_in_keys({"key 1": 1, "key-2": 2}, {"-": "_", " ": "-"})
   ... {"key-1": 1, "key_2": 2}
   ```

- For patterns with different lengths, the order does not matter, as you mentioned.
   However, if someone would wish to replace a shorter pattern first, there is currently no way of doing that.
   ```python
   >>> _replace_in_keys({"key 1": 1, "key-2": 2}, {" ": "-", "key-": "key0"})
   ... {"key-1": 1, "key02": 2}  # desired: {"key01": 1, "key02": 2}
   ```
   It would be possible to allow lists of tuples to fix the ordering, e.g. using
   ```python
   try:
       items = sorted(d.items(), ...)
   except AttributeError:
       items = d
   ```
   so that
   ```python
   >>> _replace_in_keys({"key 1": 1, "key-2": 2}, [(" ", "-"), ("key-", "key0")])
   ... {"key01": 1, "key02": 2}
   ```
   but that seems to add complexity that we can avoid by relying on `dict`s having a pre-defined order.

Therefore, I would argue that using the `dict`-ordering with proper documentation should result in the most consistent and clear behaviour, with the additional benefit of leaving a bit more freedom to the user.

**Comment by sphh** [comment] 2022-09-18 09:32
Thanks for the examples. I do see the problem now. (I didn't had this case on the screen, because they don't make sense neither in `load`ing nor in `read`ing mode.)

If I'm not wrong, this
```python3
>>> _replace_in_keys({"key 1": 1, "key-2": 2}, {" ": "-", "-": "_"})
... {"key_1": 1, "key_2": 2}
```
happens, because the replacement is recursive (" " is replaced with "-" which is replaced with "_"). IMHO I would expect the following result:
```python3
>>> _replace_in_keys({"key 1": 1, "key-2": 2}, {" ": "-", "-": "_"})
... {"key-1": 1, "key_2": 2}
```

Wouldn't this be the most consistent approach also covering this (invalid) border case. My feeling is, that this might really require regular expressions (but I have to investigate, if that is doable with regex) … Alternatively it would be a two-step process to break the recursive replacements:
1. " "→<special character1>; "-"→`<special character2>`
2. `<special character1>`→"-"; `<special character2>`→"_"

The `<special character>`s must not be valid characters for Python variables but unicode characters and they must not occur in `key_modifiers.keys()` or `key_modifiers.values()` … This can be done, but adds a bit of complexity.

If I understand the implications correctly, your suggestion of using `dict`-ordering does not resolve the problem with recursive replacements.

**Comment by hoedt** [comment] 2022-09-18 10:09
I created a branch to track the progress of this feature. It includes the transition from `io` to `config` as well as the tests that I have written thus far. The tests should reflect the expected behaviour you outlined in this thread. I thought this might be helpful.

Are you working on a fix, or should I look into it?

**Comment by sphh** [comment] 2022-09-18 11:24
I certainly can have a look.

Which approach do you prefer?
1. The Two-Step replacement.
2. Using regular expressions.

**Comment by hoedt** [comment] 2022-09-18 11:47
I have no explicit preference for one or the other. I tend to like simple/elegant solutions, but that is of course very hand-wavy.
Whatever works should be fine in the end, I guess.

**Comment by hoedt** [comment] 2022-09-23 18:58
This feature has been merged in the main branch now (together with tests and README update).

**Closed by hoedt** 2022-09-23 18:58 UTC
Labels: enhancement
